mir3/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # admin
    url(r'^admin/', include(admin.site.urls)),

    # home page
    url(r'^$', 'ui.views.homePage', name='home'),

    # search result page
    url(r'^search$', 'search.views.search', name='search'),

    # crawl page, starts crawl, crawl progress and clear current dataset
    url(r'^crawl$', 'ui.views.crawlPage', name='crawl'),
    url(r'^crawl/start$', 'search.views.crawl_start', name='crawl-start'),
    url(r'^crawl/progress$', 'search.views.crawl_progress', name='crawl-progress'),
    url(r'^clear$', 'search.views.clear', name='clear'),

    # index page
    url(r'^index$', 'ui.views.indexPage', name='index'),
    url(r'^index/select$', 'search.views.index_select', name='index-select'),
    url(r'^index/create', 'search.views.index_create', name='index-create'),
)

search/models.py
from django.contrib import admin
from django.db import models

# Create your models here.
TRAVERSAL_METHODS = ((1, 'BFS'), (2, 'DFS'))
YES_NO = ((True, 'Yes'), (False, 'No'))

class Crawl(models.Model):
    """
    Model for every crawl in web. Date and time, traversal method, max number of docs and ...
    """
    docs = models.IntegerField()
    datetime = models.DateTimeField()
    method = models.SmallIntegerField(choices=TRAVERSAL_METHODS)
    url = models.CharField(max_length=100)

    def __unicode__(self):
        return "%s, %s, %d docs" % (self.datetime.strftime('%y/%m/%d - %H:%M'), self.get_method_display(), self.docs)


class Index(models.Model):
    """
    Model for index. Index options such as page rank, stemming and stop words elimination
    """
    name = models.CharField(max_length=30, unique=True)
    stopwords = models.BooleanField(choices=YES_NO)
    stemming = models.BooleanField(choices=YES_NO)
    pagerank = models.BooleanField(choices=YES_NO)
    selected = models.BooleanField(default=False)

    def __unicode__(self):
        return self.name


admin.site.register(Crawl)
admin.site.register(Index)

ui/models.py
from django.db import models

# Create your models here.

search/views.py
import json
import os
import shutil
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http.response import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render
from search.crawler import Crawler
from search.funcs import *
# from search.funcs import createIndex
from search.models import Crawl, Index
from ui.funcs import jsonResponse


def crawl_start(request):
    """
    Starts a crawl
    """
    if Crawler.isRunning():
        return jsonResponse({'Error': 1})
    else:
        url = request.POST.get('url') or 'http://en.wikipedia.org/wiki/information_retrieval'
        try:
            max = int(request.POST.get('max'))
        except:
            max = 1
        method = request.POST.get('method') or 'DFS'

        crawler = Crawler(url, max, method)
        Crawler.setInstance(crawler)
        crawler.start()
        #time.sleep(2)

    return jsonResponse({'OK': 1})


def crawl_progress(request):
    """
    Respond progress information about current crawl
    """
    crawler = Crawler.getInstance()
    docs = crawler.docs
    max = crawler.max
    p = 100 * docs // max
    state = crawler.state

    if crawler.state != 'running':
        Crawler.setInstance(None)

    context = {
        'state': state,
        'percent': '{0}%'.format(p),
        'docs': docs,
        }
    return jsonResponse(context)


def clear(request):
    """
    Clears the current dataset
    """
    try:
        # no crawl in progress
        assert Crawler.getInstance() is None or Crawler.getInstance().state != 'running'
        # clear corpus
        shutil.rmtree(Crawler.corpus)
        os.makedirs(Crawler.corpus)
        # clear crawls history
        Crawl.objects.all().delete()
        # respond OK
        return HttpResponse('<p class="text-success">Dataset is now clear.</p>')
    except Exception, e:
        return HttpResponseForbidden('<p class="text-danger">Cannot clear dataset now.</p>')


def index_create(request):
    name = request.POST.get('name')
    stopwords = request.POST.get('stopwords') == '1'
    stemming = request.POST.get('stemming') == '1'
    pagerank = request.POST.get('pagerank') == '1'
    if Index.objects.filter(name = name).exists():
        return HttpResponseForbidden()
    else:
        createIndex(dirc = Crawler.corpus, name = name, pagerank = pagerank, stopwords = stopwords, stemming = stemming)
        selected = not Index.objects.filter(selected = True).exists()
        Index.objects.create(name = name, stopwords = stopwords, stemming = stemming, pagerank = pagerank, selected = selected)
        indices = Index.objects.all()
        return render(request, '_index-list.html', {'indices': indices})

def index_select(request):
    pk = int(request.POST.get('id'))
    Index.objects.update(selected = False)
    Index.objects.filter(pk = pk).update(selected = True)
    indices = Index.objects.all()
    return render(request, '_index-list.html', {'indices': indices})

def search(request):
    """
    Searches the query in the current index and retrieve relevant documents
    """

    index = Index.objects.filter(selected = True)
    if index:
        index = index[0]
    else:
        return render(request, 'result.html', {'error': 'Sorry, Sharif Search is not available right now!'})

    query = request.GET.get('query')
    if query:
        words = query.split(' ')

        # give query to search engine and retrieve ids
        ids = getDocs(index.name, query, index.stemming)

        docs = []
        # representing docs
        for i in ids:
            try:
                with open(Crawler.corpus + i, 'r') as inp:
                    doc = json.load(inp)
            except:
                continue
            docs.append({
                'id': i,
                'title': bold_matches(doc['title'], words),
                'url': doc['url'],
                'summery': bold_matches(doc['summery'], words)
            })

        # pagination
        paginator = Paginator(docs, 10)
        page = request.GET.get('page')
        try:
            docs = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            docs = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            docs = paginator.page(paginator.num_pages)
        pageLink = '?query={0}&page='.format(query)

        # render
        return render(request, 'result.html', {'query': query, 'docs': docs, 'pageLink': pageLink})
    else:
        return HttpResponseRedirect('/')

ui/views.py
# Create your views here.
import os
from django.shortcuts import render
from search.crawler import Crawler
from search.models import Crawl, Index
from ui.funcs import sizefmt, get_size


def homePage(request):
    return render(request, 'home.html', {})


def crawlPage(request):

    crawls = Crawl.objects.order_by('-datetime')
    corpus = Crawler.corpus
    docs = len(os.listdir(corpus))
    space = sizefmt(get_size(corpus))

    return render(request, 'crawl.html', {'crawls': crawls, 'docs': docs, 'space': space})


def indexPage(request):
    indices = Index.objects.all()
    return render(request, 'index.html', {'indices': indices})

ui/templates/_index-list.html
<div class="col-xs-5">
    <div class="form-group col-xs-10">
        <label>Indices List</label>
        <select id="data-list" class="form-control">
            {% for index in indices %}
                <option value="{{ index.pk }}"{% if index.selected %} selected{% endif %}>{{ index }}</option>
            {% endfor %}
        </select>
    </div>
</div>

<div class="col-xs-7">
    <p class="text-strong">Index details</p>
    {% for index in indices %}
        <ul class="data-details" data-id="{{ index.pk }}" {% if not index.selected %}style="display: none"{% endif %}>
            <li>
                <strong>Index name</strong>
                {{ index.name }}
                {% if index.selected %}<span class="label label-success">Current</span>{% endif %}
            </li>
            <li>
                <strong>Stop words elimination</strong>
                {{ index.get_stopwords_display }}
            </li>
            <li>
                <strong>Stemming</strong>
                {{ index.get_stemming_display }}
            </li>
            <li>
                <strong>Page rank</strong>
                {{ index.get_pagerank_display }}
            </li>
        </ul>
    {% endfor %}
</div>

ui/templates/crawl.html
{% extends 'home.html' %}

{% block body %}
    <div class="section">
        <h1><i class="glyphicon glyphicon-cloud-download"></i>
            Crawling
            <br/>
            <small>Go through web and get as much as you want!</small>
        </h1>
    </div>

    <div class="section">
        <h2>Current dataset</h2>
        {% if crawls %}
        <div class="row">
            <div class="col-xs-5">
                <ul>
                    <li>
                        <strong>Number of documents</strong>
                        {{ docs }} docs
                    </li>
                    <li>
                        <strong>Dataset space</strong>
                        {{ space }}
                    </li>
                </ul>

                <div class="form-group col-xs-10">
                    <label>Crawl History</label>
                    <select id="data-list" class="form-control">
                        {% for crawl in crawls %}
                            <option value="{{ crawl.pk }}">{{ crawl }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>

            <div class="col-xs-7">
                <p class="text-strong">Crawl details</p>
                {% for crawl in crawls %}
                    <ul class="data-details" data-id="{{ crawl.pk }}" {% if not forloop.first %}style="display: none"{% endif %}>
                        <li>
                            <strong>Crawl time</strong>
                            {{ crawl.datetime | date:"y/m/d - H:i" }}
                            {% if forloop.first %}<span class="label label-success">Newest</span>{% endif %}
                        </li>
                        <li>
                            <strong>Start URL</strong>
                            <a href="{{ crawl.url }}">{{ crawl.url }}</a>
                        </li>
                        <li>
                            <strong>Traversal method</strong>
                            {{ crawl.get_method_display }}
                        </li>
                        <li>
                            <strong>Docs retrieved</strong>
                            {{ crawl.docs }} docs
                        </li>
                    </ul>
                {% endfor %}
            </div>
            <button id="clear-dataset" class="btn btn-danger pull-right" data-url="{% url 'clear' %}">Clear dataset</button>
            <div class="clearfix"></div>
        </div>
        {% else %}
            <p class="text-muted">Dataset is empty.</p>
        {% endif %}
    </div>

    <div class="section">
        <h2>
            Start a crawl
            <br/>
            <small>Add new documents to the current dataset</small>
        </h2>
        <form action="" method="post" class="row">
            <div class="form-group col-xs-6">
                <label for="root">Start URL</label>
                <input class="form-control" type="url" name="root" value="http://en.wikipedia.org/wiki/Information_Retrieval" />
            </div>

            <div class="form-group col-xs-3">
                <label for="max">Number of Documents</label>
                <input class="form-control" type="number" name="max" value="200" />
            </div>

            <div class="clearfix"></div>

            <div class="form-group col-xs-6">
                <label>Traversal Method</label>
                <div class="radio">
                    <label>
                        <input type="radio" name="method" value="BFS" checked />
                        Breath First Search, for close topics and exact search
                    </label>
                </div>
                <div class="radio">
                    <label>
                        <input type="radio" name="method" value="DFS" />
                        Depth First Search, for wide topics and general search
                    </label>

                </div>
            </div>

            <div id="progress-box" class="form-group col-xs-6" style="display: none">
                <label>
                    Crawling the web...
                </label>
                <div>
                    <span id="progress-text">0% (0 docs)</span>
                    <div class="progress">
                        <div id="progress-bar" class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0;"></div>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>

            <button id="crawl-start" class="btn btn-primary pull-right" data-url="{% url 'crawl-start' %}" data-progress-url="{% url 'crawl-progress' %}">Start Crawling</button>

        </form>
    </div>
{% endblock %}

ui/templates/home.html
<!DOCTYPE html>
<html>
<head>
    <title>
        Sharif Search Engine
    </title>

    <link rel="stylesheet" href="{{ STATIC_URL }}bootstrap.css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}home.css" />
    {% block css %}{% endblock %}
    <script type="text/javascript" src="{{ STATIC_URL }}jquery-1.10.1.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}bootstrap.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}home.js"></script>
    {% block js %}{% endblock %}
</head>
<body>
    <div id="header">
    {% block header %}
        <div class="title pull-left">
            <img src="{{ STATIC_URL }}images/sharif_logo.png" />
        </div>
        <ul class="nav nav-pills menus">
            <li>
                <a href="{% url 'search' %}">
                    <i class="glyphicon glyphicon-search"></i>
                    Search
                </a>
            </li>
            <li class="separator"><a>|</a></li>
            <li>
                <a href="{% url 'index' %}">
                    <i class="glyphicon glyphicon-list"></i>
                    Index
                </a>
            </li>
            <li class="separator"><a>|</a></li>
            <li>
                <a href="{% url 'crawl' %}">
                    <i class="glyphicon glyphicon-cloud-download"></i>
                    Crawl
                </a>
            </li>
        </ul>
    {% endblock %}
    </div>

    <div id="body">
    {% block body %}
        <div class="search-box">
            <img class="logo" src="{{ STATIC_URL }}images/logo.png" />
            <form action="{% url 'search' %}" method="get">
                <div class="form-group" style="position: relative">
                    <input type="text" name="query" placeholder="What do you need" class="form-control query-box"/>
                    <i id="search-placeholder" class="glyphicon glyphicon-search text-muted"></i>
                </div>
                <!--
                <div class="form-group">
                    <button class="btn btn-primary pull-right">
                        <i class="glyphicon glyphicon-search"></i>
                        Search
                    </button>
                </div>
                -->
            </form>
        </div>
    {% endblock %}
    </div>

    <div id="footer">
    {% block footer %}
    <p class="text-center">
    &copy; Copyright by Hamed Moghimi &amp; Mina Tahmasbi - 2014
    </p>
    {% endblock %}
    </div>
</body>
</html>

ui/templates/index.html
{% extends 'home.html' %}

{% block body %}
    <div class="section">
        <h1><i class="glyphicon glyphicon-list"></i>
            Indexing
            <br/>
            <small>Index your data set</small>
        </h1>
    </div>

    <div class="section" id="index-list">
        <h2>Current indices</h2>
        {% if indices %}
            <div class="row">
                {% include '_index-list.html' %}
                <button id="index-select" class="btn btn-primary pull-right" data-url="{% url 'index-select' %}">Select index</button>
            </div>
        {% else %}
            <p class="text-muted">No index found.</p>
        {% endif %}
    </div>

    <div class="section">
        <h2>Create new index</h2>
        <form action="" method="post" class="row">
            <div class="form-group col-xs-6">
                <label for="name">Index name</label>
                <input class="form-control" type="text" name="name" placeholder="type a name for index" />
            </div>

            <div class="form-group col-xs-6">
                <label>Use page rank?</label>
                <div class="radio">
                    <label>
                        <input type="radio" name="pagerank" value="1" checked/> Yes
                    </label>
                </div>
                <div class="radio">
                    <label>
                        <input type="radio" name="pagerank" value="0" /> No
                    </label>

                </div>
            </div>

            <div class="clearfix"></div>

            <div class="form-group col-xs-6">
                <label>Eliminate stop words?</label>
                <div class="radio">
                    <label>
                        <input type="radio" name="stopwords" value="1" checked/> Yes
                    </label>
                </div>
                <div class="radio">
                    <label>
                        <input type="radio" name="stopwords" value="0" /> No
                    </label>

                </div>
            </div>

            <div class="form-group col-xs-6">
                <label>Use stemming?</label>
                <div class="radio">
                    <label>
                        <input type="radio" name="stemming" value="1" checked/> Yes
                    </label>
                </div>
                <div class="radio">
                    <label>
                        <input type="radio" name="stemming" value="0" /> No
                    </label>

                </div>
            </div>

            <div class="clearfix"></div>

            <button id="index-create" class="btn btn-primary pull-right" data-url="{% url 'index-create' %}">Create index</button>

            <p id="success-message" class="message text-success pull-right" style="display: none">New index is created</p>
            <p id="error-message" class="message text-danger pull-right" style="display: none">Index with the same name exists!</p>

        </form>
    </div>
{% endblock %}

ui/templates/result.html
{% extends 'home.html' %}

{% block body %}
    <div class="section">
        <form action="" method="get" class="row search-box-inline">
            <img src="{{ STATIC_URL }}images/logo.png" class="col-xs-2" />
            <div class="col-xs-4">
                <div style="position: relative">
                    <input type="text" name="query" placeholder="What do you need" class="form-control query-box" value="{{ query }}"/>
                    <i id="search-placeholder" class="glyphicon glyphicon-search text-muted"></i>
                </div>
            </div>
            <div class="col-xs-2">
                <button class="btn btn-primary">Search</button>
            </div>
        </form>
    </div>

    <div class="section">

        {% if error %}
            <h3 class="text-center text-danger">
                Sorry, Sharif Search is not available right now!
            </h3>
        {% else %}
        {% for doc in docs %}
            <div class="search-result">
                <a href="{{ doc.url }}">{{ doc.title|safe }}</a>
                <span class="text-success">{{ doc.url }}</span>
                <p class="text-justified">
                    {{ doc.summery|safe }}
                </p>
            </div>
        {% empty %}
            <h2 class="text-center">
            <small>No result found</small>
            </h2>
        {% endfor %}

        {% if docs.paginator.num_pages > 1 %}
        <div class="text-center">
            <ul class="pagination">
                {% if docs.has_previous %}
                    <li><a href="{{ pageLink }}{{ docs.previous_page_number }}">&laquo;</a></li>
                {% endif %}
                {% for i in docs.paginator.page_range %}
                    <li{% if docs.number == i %} class="active"{% endif %}><a href="{{ pageLink }}{{ i }}">{{ i }}</a></li>
                {% endfor %}
                {% if docs.has_next %}
                    <li><a href="{{ pageLink }}{{ docs.next_page_number }}">&raquo;</a></li>
                {% endif %}
            </ul>
        </div>
        {% endif %}
        {% endif %}
    </div>
{% endblock %}